### ISSUE TITLE
Don't run Github workflow CI on documentation PRs

### ISSUE THREAD

**Issue by wldevries** [MonoGame/MonoGame#7997]
Currently the Github CI workflow runs for every pull request and every single push. Having the CI only run when there are code changes to check might save some money.

I have no experience with Github workflows, but a file exclusion filter might do the trick.

```yaml
on:
  push:
    paths-ignore:
     - 'Documentation/**'
     - 'Images/**'
  pull_request:
    paths-ignore:
     - 'Documentation/**'
     - 'Images/**'
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
